import type { FlowGraph } from "./graphTypes.js";

export const SIGAL_OPENING =
  "שלום {{customer_first_name}}, מדברת {{agent_name}} מ-YES. שיחה זו מוקלטת לצורכי איכות. האם אוכל להציע לך כמה מבצעים מיוחדים שיש לנו היום?";

export const SIGAL_QUALIFY =
  "מצוין! יש לי מבצעים על טלוויזיה, אינטרנט וחבילות משולבות — על מה תרצה לשמוע?";

export const SOLD_GOODBYE =
  "נהדר! נציג אנושי יחזור אליך בהקדם לסגירת העסקה. תודה רבה, יום טוב!";

export function createDefaultStarterFlow(): FlowGraph {
  return {
    startNodeId: "start",
    nodes: [
      {
        id: "start",
        type: "speak",
        label: "פתיחה",
        text: SIGAL_OPENING,
        useLlm: false,
        position: { x: 250, y: 0 },
      },
      { id: "listen_open", type: "listen", label: "האזנה לפתיחה", position: { x: 250, y: 120 } },
      { id: "route_open", type: "intent_route", label: "ניתוב פתיחה", position: { x: 250, y: 240 } },
      {
        id: "small_talk_reply",
        type: "speak",
        label: "שיחת חולין",
        text: "תודה ששאלת! אני כאן ושמחה לשוחח. איך אני יכולה לעזור לך היום?",
        useLlm: true,
        position: { x: -200, y: 380 },
      },
      {
        id: "insult_reply",
        type: "speak",
        label: "גבול אישי",
        text: "אני מבינה שאתה כועס, אבל לא נעים לשמוע שפה כזו. בוא נמשיך בכבוד.",
        useLlm: false,
        position: { x: 500, y: 380 },
      },
      {
        id: "qualify",
        type: "speak",
        label: "התאמה",
        text: SIGAL_QUALIFY,
        position: { x: 100, y: 500 },
      },
      {
        id: "pitch",
        type: "speak",
        label: "הצגת חבילה",
        text: "יש לנו חבילת טריפל מצוינת החל מ-149 שקלים לחודש. היא כוללת ערוצי ספורט, ילדים, אינטרנט סיבים וטלפון.",
        useLlm: true,
        position: { x: 100, y: 620 },
      },
      { id: "listen_pitch", type: "listen", label: "האזנה להצעה", position: { x: 100, y: 740 } },
      { id: "route_objections", type: "intent_route", label: "התנגדויות", position: { x: 100, y: 860 } },
      {
        id: "price_reply",
        type: "speak",
        label: "מחיר",
        text: "אני מבינה. יש לנו גם חבילות קטנות יותר החל מ-99 שקלים, ואפשר לשלב מבצעים.",
        useLlm: true,
        position: { x: -250, y: 1020 },
      },
      {
        id: "channel_reply",
        type: "speak",
        label: "שאלת ערוץ",
        text: "אשמח לפרט על הערוץ ששאלת לפי הקטלוג שלנו.",
        useLlm: true,
        position: { x: -50, y: 1020 },
      },
      {
        id: "packet_reply",
        type: "speak",
        label: "שאלת חבילה",
        text: "אשמח לפרט מה כלול בחבילה לפי הקטלוג.",
        useLlm: true,
        position: { x: 150, y: 1020 },
      },
      {
        id: "internet_reply",
        type: "speak",
        label: "שאלת אינטרנט",
        text: "אשמח לפרט על מהירויות האינטרנט והמחירים שלנו.",
        useLlm: true,
        position: { x: 350, y: 1020 },
      },
      {
        id: "router_reply",
        type: "speak",
        label: "שכירות נתב",
        text: "אשמח לפרט על עלויות שכירות הנתב לפי הקטלוג.",
        useLlm: true,
        position: { x: 550, y: 1020 },
      },
      {
        id: "options_reply",
        type: "speak",
        label: "השוואת אפשרויות",
        text: "אשמח להציג לך את האפשרויות השונות שיש לנו.",
        useLlm: true,
        position: { x: 750, y: 1020 },
      },
      {
        id: "close",
        type: "speak",
        label: "סגירה",
        text: "האם תרצה לסגור את העסקה היום ולקבל את כל הפרטים?",
        position: { x: 450, y: 1140 },
      },
      { id: "listen_close", type: "listen", label: "האזנה לסגירה", position: { x: 450, y: 1260 } },
      { id: "route_close", type: "intent_route", label: "ניתוב סגירה", position: { x: 450, y: 1380 } },
      {
        id: "confirm_refusal",
        type: "speak",
        label: "אישור סירוב",
        text: "הבנתי. רק לוודא — האם אתה בטוח שאתה לא מעוניין?",
        useLlm: false,
        position: { x: 650, y: 500 },
      },
      { id: "listen_confirm", type: "listen", label: "האזנה לאישור", position: { x: 650, y: 620 } },
      { id: "route_confirm", type: "intent_route", label: "ניתוב אישור סירוב", position: { x: 650, y: 740 } },
      {
        id: "goodbye_refused",
        type: "speak",
        label: "פרידה",
        text: "תודה רבה, יום טוב!",
        useLlm: false,
        position: { x: 850, y: 860 },
      },
      {
        id: "goodbye_sold",
        type: "speak",
        label: "פרידה לאחר עניין",
        text: SOLD_GOODBYE,
        useLlm: false,
        position: { x: 350, y: 1400 },
      },
      { id: "end_sold", type: "end", label: "נמכר", outcome: "sold", position: { x: 350, y: 1520 } },
      { id: "end_refused", type: "end", label: "סירוב", outcome: "refused", position: { x: 850, y: 980 } },
      { id: "end_callback", type: "end", label: "חזרה", outcome: "callback", position: { x: 950, y: 1140 } },
      {
        id: "callback_reply",
        type: "speak",
        label: "חזרה מאוחרת",
        text: "בשמחה, מתי יהיה נוח לחזור אליך?",
        position: { x: 950, y: 1020 },
      },
    ],
    edges: [
      { id: "e1", source: "start", target: "listen_open" },
      { id: "e2", source: "listen_open", target: "route_open" },
      { id: "e3", source: "route_open", target: "qualify", intentId: "greeting_ack", label: "מסכים" },
      { id: "e4", source: "route_open", target: "small_talk_reply", intentId: "small_talk", label: "שיחת חולין" },
      { id: "e5", source: "route_open", target: "insult_reply", intentId: "insult_profanity", label: "עלבון" },
      { id: "e6", source: "route_open", target: "confirm_refusal", intentId: "not_interested", label: "לא מעוניין" },
      { id: "e7", source: "route_open", target: "callback_reply", intentId: "callback", label: "חזרה" },
      { id: "e8", source: "route_open", target: "qualify", isDefault: true, label: "ברירת מחדל" },
      { id: "e9", source: "small_talk_reply", target: "qualify" },
      { id: "e10", source: "insult_reply", target: "listen_open" },
      { id: "e11", source: "qualify", target: "pitch" },
      { id: "e12", source: "pitch", target: "listen_pitch" },
      { id: "e13", source: "listen_pitch", target: "route_objections" },
      { id: "e14", source: "route_objections", target: "price_reply", intentId: "price_objection", label: "מחיר" },
      { id: "e15", source: "route_objections", target: "channel_reply", intentId: "ask_channel", label: "ערוץ" },
      { id: "e16", source: "route_objections", target: "packet_reply", intentId: "ask_packet", label: "חבילה" },
      { id: "e17", source: "route_objections", target: "internet_reply", intentId: "ask_internet", label: "אינטרנט" },
      { id: "e18", source: "route_objections", target: "router_reply", intentId: "ask_router_rental", label: "נתב" },
      { id: "e19", source: "route_objections", target: "options_reply", intentId: "ask_options_compare", label: "אפשרויות" },
      { id: "e20", source: "route_objections", target: "small_talk_reply", intentId: "small_talk", label: "שיחת חולין" },
      { id: "e21", source: "route_objections", target: "insult_reply", intentId: "insult_profanity", label: "עלבון" },
      { id: "e22", source: "route_objections", target: "confirm_refusal", intentId: "not_interested", label: "סירוב" },
      { id: "e23", source: "route_objections", target: "callback_reply", intentId: "callback", label: "חזרה" },
      { id: "e24", source: "route_objections", target: "close", intentId: "greeting_ack", label: "ממשיך" },
      { id: "e25", source: "route_objections", target: "close", isDefault: true, label: "ברירת מחדל" },
      { id: "e26", source: "price_reply", target: "listen_pitch" },
      { id: "e27", source: "channel_reply", target: "listen_pitch" },
      { id: "e28", source: "packet_reply", target: "listen_pitch" },
      { id: "e29", source: "internet_reply", target: "listen_pitch" },
      { id: "e30", source: "router_reply", target: "listen_pitch" },
      { id: "e31", source: "options_reply", target: "listen_pitch" },
      { id: "e32", source: "close", target: "listen_close" },
      { id: "e33", source: "listen_close", target: "route_close" },
      { id: "e34", source: "route_close", target: "goodbye_sold", intentId: "agree_purchase", label: "רכישה" },
      { id: "e35", source: "route_close", target: "confirm_refusal", intentId: "not_interested", label: "סירוב" },
      { id: "e36", source: "route_close", target: "end_callback", intentId: "callback", label: "חזרה" },
      { id: "e37", source: "route_close", target: "close", isDefault: true, label: "ברירת מחדל" },
      { id: "e38", source: "confirm_refusal", target: "listen_confirm" },
      { id: "e39", source: "listen_confirm", target: "route_confirm" },
      { id: "e40", source: "route_confirm", target: "goodbye_refused", intentId: "not_interested_confirmed", label: "מאושר" },
      { id: "e41", source: "route_confirm", target: "goodbye_refused", intentId: "not_interested", label: "חוזר סירוב" },
      { id: "e42", source: "route_confirm", target: "pitch", intentId: "greeting_ack", label: "ממשיך" },
      { id: "e43", source: "route_confirm", target: "pitch", isDefault: true, label: "ברירת מחדל" },
      { id: "e44", source: "goodbye_refused", target: "end_refused" },
      { id: "e45", source: "callback_reply", target: "end_callback" },
      { id: "e46", source: "goodbye_sold", target: "end_sold" },
    ],
  };
}

export function isSigalFlowGraph(graph: FlowGraph): boolean {
  const start = graph.nodes.find((n) => n.id === "start");
  return Boolean(start?.type === "speak" && start.text.includes("סיגל"));
}
