import type { FlowGraph } from "./graphTypes.js";

export function createDefaultStarterFlow(): FlowGraph {
  return {
    startNodeId: "start",
    nodes: [
      {
        id: "start",
        type: "speak",
        label: "פתיחה",
        text: "שלום {{customer_full_name}}, מדברת נציגת YES. שיחה זו מוקלטת לצורכי איכות. האם זה זמן נוח לשמוע על חבילות YES?",
        useLlm: false,
        position: { x: 250, y: 0 },
      },
      {
        id: "listen_open",
        type: "listen",
        label: "האזנה לפתיחה",
        position: { x: 250, y: 120 },
      },
      {
        id: "route_open",
        type: "intent_route",
        label: "ניתוב פתיחה",
        position: { x: 250, y: 240 },
      },
      {
        id: "qualify",
        type: "speak",
        label: "התאמה",
        text: "מצוין! האם אתה מעוניין בטלוויזיה, אינטרנט, או חבילה משולבת?",
        position: { x: 100, y: 380 },
      },
      {
        id: "pitch",
        type: "speak",
        label: "הצגת חבילה",
        text: "יש לנו חבילת טריפל מצוינת החל מ-149 שקלים לחודש. היא כוללת ערוצי ספורט, ילדים, אינטרנט סיבים וטלפון.",
        useLlm: true,
        position: { x: 100, y: 500 },
      },
      {
        id: "listen_pitch",
        type: "listen",
        label: "האזנה להצעה",
        position: { x: 100, y: 620 },
      },
      {
        id: "route_objections",
        type: "intent_route",
        label: "התנגדויות",
        position: { x: 100, y: 740 },
      },
      {
        id: "price_reply",
        type: "speak",
        label: "מחיר",
        text: "אני מבינה. יש לנו גם חבילות קטנות יותר החל מ-99 שקלים, ואפשר לשלב מבצעים.",
        useLlm: true,
        position: { x: -150, y: 900 },
      },
      {
        id: "channel_reply",
        type: "speak",
        label: "שאלת ערוץ",
        text: "אשמח לפרט על הערוץ ששאלת לפי הקטלוג שלנו.",
        useLlm: true,
        position: { x: 50, y: 900 },
      },
      {
        id: "packet_reply",
        type: "speak",
        label: "שאלת חבילה",
        text: "אשמח לפרט מה כלול בחבילה לפי הקטלוג.",
        useLlm: true,
        position: { x: 250, y: 900 },
      },
      {
        id: "close",
        type: "speak",
        label: "סגירה",
        text: "האם תרצה לסגור את העסקה היום ולקבל את כל הפרטים?",
        position: { x: 450, y: 900 },
      },
      {
        id: "listen_close",
        type: "listen",
        label: "האזנה לסגירה",
        position: { x: 450, y: 1020 },
      },
      {
        id: "route_close",
        type: "intent_route",
        label: "ניתוב סגירה",
        position: { x: 450, y: 1140 },
      },
      {
        id: "end_sold",
        type: "end",
        label: "נמכר",
        outcome: "sold",
        position: { x: 350, y: 1280 },
      },
      {
        id: "end_refused",
        type: "end",
        label: "סירוב",
        outcome: "refused",
        position: { x: 550, y: 1280 },
      },
      {
        id: "end_callback",
        type: "end",
        label: "חזרה",
        outcome: "callback",
        position: { x: 750, y: 1280 },
      },
      {
        id: "callback_reply",
        type: "speak",
        label: "חזרה מאוחרת",
        text: "בשמחה, מתי יהיה נוח לחזור אליך?",
        position: { x: 750, y: 900 },
      },
      {
        id: "refuse_reply",
        type: "speak",
        label: "לא מעוניין",
        text: "אין בעיה, תודה על זמנך. אם תרצה בעתיד — אנחנו כאן.",
        position: { x: 550, y: 380 },
      },
    ],
    edges: [
      { id: "e1", source: "start", target: "listen_open" },
      { id: "e2", source: "listen_open", target: "route_open" },
      {
        id: "e3",
        source: "route_open",
        target: "qualify",
        intentId: "greeting_ack",
        label: "מסכים",
      },
      {
        id: "e4",
        source: "route_open",
        target: "refuse_reply",
        intentId: "not_interested",
        label: "לא מעוניין",
      },
      {
        id: "e5",
        source: "route_open",
        target: "callback_reply",
        intentId: "callback",
        label: "חזרה",
      },
      { id: "e6", source: "route_open", target: "qualify", isDefault: true, label: "ברירת מחדל" },
      { id: "e7", source: "qualify", target: "pitch" },
      { id: "e8", source: "pitch", target: "listen_pitch" },
      { id: "e9", source: "listen_pitch", target: "route_objections" },
      {
        id: "e10",
        source: "route_objections",
        target: "price_reply",
        intentId: "price_objection",
        label: "מחיר",
      },
      {
        id: "e11",
        source: "route_objections",
        target: "channel_reply",
        intentId: "ask_channel",
        label: "ערוץ",
      },
      {
        id: "e12",
        source: "route_objections",
        target: "packet_reply",
        intentId: "ask_packet",
        label: "חבילה",
      },
      {
        id: "e13",
        source: "route_objections",
        target: "close",
        intentId: "greeting_ack",
        label: "ממשיך",
      },
      {
        id: "e14",
        source: "route_objections",
        target: "refuse_reply",
        intentId: "not_interested",
        label: "סירוב",
      },
      {
        id: "e15",
        source: "route_objections",
        target: "callback_reply",
        intentId: "callback",
        label: "חזרה",
      },
      { id: "e16", source: "route_objections", target: "close", isDefault: true, label: "ברירת מחדל" },
      { id: "e17", source: "price_reply", target: "close" },
      { id: "e18", source: "channel_reply", target: "close" },
      { id: "e19", source: "packet_reply", target: "close" },
      { id: "e20", source: "close", target: "listen_close" },
      { id: "e21", source: "listen_close", target: "route_close" },
      {
        id: "e22",
        source: "route_close",
        target: "end_sold",
        intentId: "agree_purchase",
        label: "רכישה",
      },
      {
        id: "e23",
        source: "route_close",
        target: "end_refused",
        intentId: "not_interested",
        label: "סירוב",
      },
      {
        id: "e24",
        source: "route_close",
        target: "end_callback",
        intentId: "callback",
        label: "חזרה",
      },
      { id: "e25", source: "route_close", target: "close", isDefault: true, label: "ברירת מחדל" },
      { id: "e26", source: "refuse_reply", target: "end_refused" },
      { id: "e27", source: "callback_reply", target: "end_callback" },
    ],
  };
}
